.TH MapRoom 1 "Dec 2009" "" ""
.SH NAME
MapRoom \- GPS mapping (GeoTiff and vector) and GPSr management
.SH SYNOPSIS
.B maproom
[
.B \-d
|
.B \-\-debug
]
[
.B \-h
|
.B \-\-help
]
.BI \fB\-m \ FD
|
.BI \-\-monitor= FD
]
[
.B \-n
|
.B \-\-no-splash
]
[
.IR files ...
]
.SH DESCRIPTION
TODO
.SH OPTIONS
TODO
.SH SEE ALSO
TODO
.SH AUTHOR
\fIMapRoom\fR was written and is currently maintained by Oliver Eichler
\fB<oliver.eichler@gmx.de>\fR.
