.TH "QMAPTOOL" "1" "July 2014" "" ""
.SH "NAME"
QMapTool - Creating Raster Maps
.br

.SH "SYNOPSIS"
\fBqmaptool\fR\fB [ -d \fR| \fB--debug \fR] [ \fB-h \fR| \fB--help \fR] [ \fB-n \fR| \fB--no-splash \fR]
.br

.SH "DESCRIPTION"
A tool to process and referecne scanned paper maps
.br

Main features:
.br
	- Cut borders of maps
.br
	- Reference maps 
.br
	- Convert maps into GeoTiff files with a color table
.br

.SH "OPTIONS"
\fB-d\fR, \fB--debug\fR
.br
       Run with debugging output.
.br

\fB-h\fR, \fB--help\fR
.br
       Displays the help message.
.br

\fB-n, --no-splash\fR
.br
       Start without splash screen.
.br

.SH "SEE ALSO"
https://github.com/Maproom/qmapshack/wiki/DocMain
.br

.SH "AUTHOR"
QMapTool was written and is currently maintained by Oliver Eichler \fB<oliver.eichler@gmx.de>\fR.
.br
