.TH QMAPSHACK 1 "July 2014" "" ""
.SH NAME
QMapShack \- GPS mapping (GeoTiff and vector) and GPSr management
.SH SYNOPSIS
\fBqmapshack\fP [\options\fP]
[
.B \-d
|
.B \-\-debug
]
[
.B \-h
|
.B \-\-help
]
[
.B \-n
|
.B \-\-no-splash
]
[
.IR files ...
]
.SH DESCRIPTION
GPS mapping (GeoTiff and vector) and GPSr management.
QMapShack provides a versatile tool for GPS maps in GeoTiff format as well as Garmin's img vector map format.
You can also view and edit your GPX tracks. QMapShack is the successor of QLandkarteGT.
.TP
Main features:
  \- Use of several workspaces.
  \- Use several maps on a workspace.
  \- Handle data project-oriented.
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-debug\fR
Run with debugging output.
.TP
\fB\-h\fR, \fB\-\-help\fR
Displays the help message.
.TP
\fB\-n\fR, \fB\-\-no-splash\fR
Start without splash screen.
.TP
.SH SEE ALSO
<https://github.com/Maproom/qmapshack/wiki/DocMain>.
.SH AUTHOR
\fIQMapShack\fR was written and is currently maintained by Oliver Eichler
\fB<oliver.eichler@gmx.de>\fR.
