/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Source file was org.gtk.vfs.MTPVolumeMonitor.xml
 *
 * qdbusxml2cpp is Copyright (C) The Qt Company Ltd. and other contributors.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef ORG_GTK_VFS_MTPVOLUMEMONITOR_H
#define ORG_GTK_VFS_MTPVOLUMEMONITOR_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "metatypes.h"

/*
 * Proxy class for interface org.gtk.Private.RemoteVolumeMonitor
 */
class OrgGtkPrivateRemoteVolumeMonitorInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.gtk.Private.RemoteVolumeMonitor"; }

public:
    OrgGtkPrivateRemoteVolumeMonitorInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgGtkPrivateRemoteVolumeMonitorInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<bool> CancelOperation(const QString &cancellation_id)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(cancellation_id);
        return asyncCallWithArgumentList(QStringLiteral("CancelOperation"), argumentList);
    }

    inline QDBusPendingReply<> DriveEject(const QString &id, const QString &cancellation_id, uint unmount_flags, const QString &mount_op_id)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(id) << QVariant::fromValue(cancellation_id) << QVariant::fromValue(unmount_flags) << QVariant::fromValue(mount_op_id);
        return asyncCallWithArgumentList(QStringLiteral("DriveEject"), argumentList);
    }

    inline QDBusPendingReply<> DrivePollForMedia(const QString &id, const QString &cancellation_id)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(id) << QVariant::fromValue(cancellation_id);
        return asyncCallWithArgumentList(QStringLiteral("DrivePollForMedia"), argumentList);
    }

    inline QDBusPendingReply<> DriveStart(const QString &id, const QString &cancellation_id, uint flags, const QString &mount_op_id)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(id) << QVariant::fromValue(cancellation_id) << QVariant::fromValue(flags) << QVariant::fromValue(mount_op_id);
        return asyncCallWithArgumentList(QStringLiteral("DriveStart"), argumentList);
    }

    inline QDBusPendingReply<> DriveStop(const QString &id, const QString &cancellation_id, uint unmount_flags, const QString &mount_op_id)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(id) << QVariant::fromValue(cancellation_id) << QVariant::fromValue(unmount_flags) << QVariant::fromValue(mount_op_id);
        return asyncCallWithArgumentList(QStringLiteral("DriveStop"), argumentList);
    }

    inline QDBusPendingReply<bool> IsSupported()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("IsSupported"), argumentList);
    }

    inline QDBusPendingReply<GVFSMtpDriveList, GVFSMtpVolumeList, GVFSMtpMountList> List() {
      QList<QVariant> argumentList;
      return asyncCallWithArgumentList(QStringLiteral("List"), argumentList);
    }
    inline QDBusReply<GVFSMtpDriveList> List(GVFSMtpVolumeList &volumes, GVFSMtpMountList &mounts) {
      QList<QVariant> argumentList;
      QDBusMessage reply = callWithArgumentList(QDBus::Block, QStringLiteral("List"), argumentList);
      if (reply.type() == QDBusMessage::ReplyMessage && reply.arguments().size() == 3) {
        volumes = qdbus_cast<GVFSMtpVolumeList>(reply.arguments().at(1));
        mounts = qdbus_cast<GVFSMtpMountList>(reply.arguments().at(2));
      }
      return reply;
    }

    inline QDBusPendingReply<> MountOpReply(const QString &mount_op_id, int result, const QString &user_name, const QString &domain, const QString &encoded_password, int password_save, int choice, bool anonymous)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(mount_op_id) << QVariant::fromValue(result) << QVariant::fromValue(user_name) << QVariant::fromValue(domain) << QVariant::fromValue(encoded_password) << QVariant::fromValue(password_save) << QVariant::fromValue(choice) << QVariant::fromValue(anonymous);
        return asyncCallWithArgumentList(QStringLiteral("MountOpReply"), argumentList);
    }

    inline QDBusPendingReply<> MountOpReply2(const QString &mount_op_id, int result, const QString &user_name, const QString &domain, const QString &encoded_password, int password_save, int choice, bool anonymous, const QMap<QString,QDBusVariant> &expansion)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(mount_op_id) << QVariant::fromValue(result) << QVariant::fromValue(user_name) << QVariant::fromValue(domain) << QVariant::fromValue(encoded_password) << QVariant::fromValue(password_save) << QVariant::fromValue(choice) << QVariant::fromValue(anonymous) << QVariant::fromValue(expansion);
        return asyncCallWithArgumentList(QStringLiteral("MountOpReply2"), argumentList);
    }

    inline QDBusPendingReply<> MountUnmount(const QString &id, const QString &cancellation_id, uint unmount_flags, const QString &mount_op_id)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(id) << QVariant::fromValue(cancellation_id) << QVariant::fromValue(unmount_flags) << QVariant::fromValue(mount_op_id);
        return asyncCallWithArgumentList(QStringLiteral("MountUnmount"), argumentList);
    }

    inline QDBusPendingReply<> VolumeMount(const QString &id, const QString &cancellation_id, uint mount_flags, const QString &mount_op_id)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(id) << QVariant::fromValue(cancellation_id) << QVariant::fromValue(mount_flags) << QVariant::fromValue(mount_op_id);
        return asyncCallWithArgumentList(QStringLiteral("VolumeMount"), argumentList);
    }

Q_SIGNALS: // SIGNALS
 void DriveChanged(const QString &dbus_name, const QString &id, GVFSMtpDrive drive);
 void DriveConnected(const QString &dbus_name, const QString &id, GVFSMtpDrive drive);
 void DriveDisconnected(const QString &dbus_name, const QString &id, GVFSMtpDrive drive);
 void DriveEjectButton(const QString &dbus_name, const QString &id, GVFSMtpDrive drive);
 void DriveStopButton(const QString &dbus_name, const QString &id, GVFSMtpDrive drive);
 void MountAdded(const QString &dbus_name, const QString &id, GVFSMtpMount mount);
 void MountChanged(const QString &dbus_name, const QString &id, GVFSMtpMount mount);
 void MountOpAborted(const QString &dbus_name, const QString &id);
 void MountOpAskPassword(const QString &dbus_name, const QString &id, const QString &message_to_show,
                         const QString &default_user, const QString &default_domain, uint flags);
 void MountOpAskQuestion(const QString &dbus_name, const QString &id, const QString &message_to_show,
                         const QStringList &choices);
 void MountOpShowProcesses(const QString &dbus_name, const QString &id, const QString &message_to_show,
                           const QList<uint32_t> &pid, const QStringList &choices);
 void MountOpShowUnmountProgress(const QString &dbus_name, const QString &id, const QString &message_to_show,
                                 qlonglong time_left, qlonglong bytes_left);
 void MountPreUnmount(const QString &dbus_name, const QString &id, GVFSMtpMount mount);
 void MountRemoved(const QString &dbus_name, const QString &id, GVFSMtpMount mount);
 void VolumeAdded(const QString &dbus_name, const QString &id, GVFSMtpVolume volume);
 void VolumeChanged(const QString &dbus_name, const QString &id, GVFSMtpVolume volume);
 void VolumeRemoved(const QString &dbus_name, const QString &id, GVFSMtpVolume volume);
};

namespace org {
  namespace gtk {
    namespace Private {
      using RemoteVolumeMonitor = ::OrgGtkPrivateRemoteVolumeMonitorInterface;
    }
  }
}
#endif
