/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp org.kde.kmtp.Daemon.xml -p org.kde.kmtp.Daemon.h
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef ORG_KDE_KMTP_DAEMON_H
#define ORG_KDE_KMTP_DAEMON_H

#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QObject>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.kde.kmtp.Daemon
 */
class OrgKdeKmtpDaemonInterface : public QDBusAbstractInterface {
  Q_OBJECT
 public:
  static inline const char *staticInterfaceName() { return "org.kde.kmtp.Daemon"; }

 public:
  OrgKdeKmtpDaemonInterface(const QString &service, const QString &path, const QDBusConnection &connection,
                            QObject *parent = nullptr);

  ~OrgKdeKmtpDaemonInterface();

  Q_PROPERTY(QString version READ version)
  inline QString version() const { return qvariant_cast<QString>(property("version")); }

 public Q_SLOTS:  // METHODS
  inline QDBusPendingReply<QList<QDBusObjectPath> > listDevices() {
    QList<QVariant> argumentList;
    return asyncCallWithArgumentList(QStringLiteral("listDevices"), argumentList);
  }

 Q_SIGNALS:  // SIGNALS
  void devicesChanged();
};

namespace org {
namespace kde {
namespace kmtp {
typedef ::OrgKdeKmtpDaemonInterface Daemon;
}
}  // namespace kde
}  // namespace org
#endif
