/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Source file was org.gtk.vfs.Mount.xml
 *
 * qdbusxml2cpp is Copyright (C) The Qt Company Ltd. and other contributors.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "org.gtk.vfs.Mount.h"

/*
 * Implementation of interface class OrgGtkVfsMountInterface
 */

OrgGtkVfsMountInterface::OrgGtkVfsMountInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgGtkVfsMountInterface::~OrgGtkVfsMountInterface()
{
}

