/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Source file was org.gtk.vfs.MountTracker.xml
 *
 * qdbusxml2cpp is Copyright (C) The Qt Company Ltd. and other contributors.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef ORG_GTK_VFS_MOUNTTRACKER_H
#define ORG_GTK_VFS_MOUNTTRACKER_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "metatypes.h"

/*
 * Proxy class for interface org.gtk.vfs.MountTracker
 */
class OrgGtkVfsMountTrackerInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.gtk.vfs.MountTracker"; }

public:
    OrgGtkVfsMountTrackerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgGtkVfsMountTrackerInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QStringList> ListMountTypes()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("ListMountTypes"), argumentList);
    }

    inline QDBusPendingReply<GVFSMountableList> ListMountableInfo()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("ListMountableInfo"), argumentList);
    }

    inline QDBusPendingReply<GVFSMountList> ListMounts()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("ListMounts"), argumentList);
    }

    inline QDBusPendingReply<GVFSMountList> ListMounts2(bool user_visible_only)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(user_visible_only);
        return asyncCallWithArgumentList(QStringLiteral("ListMounts2"), argumentList);
    }

    inline QDBusPendingReply<GVFSMount> LookupMount(GVFSMountSpec mount_spec)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(mount_spec);
        return asyncCallWithArgumentList(QStringLiteral("LookupMount"), argumentList);
    }

    inline QDBusPendingReply<GVFSMount> LookupMountByFusePath(const QByteArray &fuse_path)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(fuse_path);
        return asyncCallWithArgumentList(QStringLiteral("LookupMountByFusePath"), argumentList);
    }

    inline QDBusPendingReply<> MountLocation(GVFSMountSpec mount_spec, GVFSMountSource mount_source)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(mount_spec) << QVariant::fromValue(mount_source);
        return asyncCallWithArgumentList(QStringLiteral("MountLocation"), argumentList);
    }

    inline QDBusPendingReply<> RegisterFuse()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("RegisterFuse"), argumentList);
    }

    inline QDBusPendingReply<> RegisterMount(const QDBusObjectPath &obj_path, const QString &display_name, const QString &stable_name, const QString &x_content_types, const QString &icon, const QString &symbolic_icon, const QString &prefered_filename_encoding, bool user_visible, GVFSMountSpec mount_spec, const QByteArray &default_location)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(obj_path) << QVariant::fromValue(display_name) << QVariant::fromValue(stable_name) << QVariant::fromValue(x_content_types) << QVariant::fromValue(icon) << QVariant::fromValue(symbolic_icon) << QVariant::fromValue(prefered_filename_encoding) << QVariant::fromValue(user_visible) << QVariant::fromValue(mount_spec) << QVariant::fromValue(default_location);
        return asyncCallWithArgumentList(QStringLiteral("RegisterMount"), argumentList);
    }

    inline QDBusPendingReply<> UnregisterMount(const QDBusObjectPath &obj_path)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(obj_path);
        return asyncCallWithArgumentList(QStringLiteral("UnregisterMount"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void Mounted(GVFSMount mount);
    void Unmounted(GVFSMount mount);
};

namespace org {
  namespace gtk {
    namespace vfs {
      using MountTracker = ::OrgGtkVfsMountTrackerInterface;
    }
  }
}
#endif
