/**********************************************************************************************

This file was autogenerated by src/qmapshack/plugin/wrappers/createWrapper.py

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

**********************************************************************************************/

#ifndef CACTIVITYTRKWRAPPER_H
#define CACTIVITYTRKWRAPPER_H

#include <qobject.h>
#include "gis/trk/CActivityTrk.h"



class CActivityTrkWrapper : public QObject
 {
    Q_OBJECT
public slots:
    static void init(CActivityTrk* wrappedObj) { return wrappedObj->init();}
    static void release(CActivityTrk* wrappedObj) { return wrappedObj->release();}
    void update(CActivityTrk* wrappedObj) { return wrappedObj->update();}
    void updateFlags(CActivityTrk* wrappedObj) { return wrappedObj->updateFlags();}
    qint32 getActivityCount(CActivityTrk* wrappedObj) { return wrappedObj->getActivityCount();}
    void getActivityNames(CActivityTrk* wrappedObj, QStringList&  names) { return wrappedObj->getActivityNames(names);}
    void printSummary(CActivityTrk* wrappedObj, QString&  str) { return wrappedObj->printSummary(str);}
}; 

#endif