/**********************************************************************************************

This file was autogenerated by src/qmapshack/plugin/wrappers/createWrapper.py

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

**********************************************************************************************/

#ifndef CDBFOLDERLOSTFOUNDWRAPPER_H
#define CDBFOLDERLOSTFOUNDWRAPPER_H

#include <qobject.h>
#include "gis/db/CDBFolderLostFound.h"



class CDBFolderLostFoundWrapper : public QObject
 {
    Q_OBJECT
public slots:
    void update(CDBFolderLostFound* wrappedObj, CEvtW2DAckInfo *  info) { return wrappedObj->update(info);}
    bool update(CDBFolderLostFound* wrappedObj) { return wrappedObj->update();}
    void expanding(CDBFolderLostFound* wrappedObj) { return wrappedObj->expanding();}
    void clear(CDBFolderLostFound* wrappedObj) { return wrappedObj->clear();}
    bool delItem(CDBFolderLostFound* wrappedObj, CDBItem *  item) { return wrappedObj->delItem(item);}
}; 

#endif