/**********************************************************************************************

This file was autogenerated by src/qmapshack/plugin/wrappers/createWrapper.py

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

**********************************************************************************************/

#ifndef CDBFOLDERMYSQLWRAPPER_H
#define CDBFOLDERMYSQLWRAPPER_H

#include <qobject.h>
#include "gis/db/CDBFolderMysql.h"



class CDBFolderMysqlWrapper : public QObject
 {
    Q_OBJECT
public slots:
    const QString& getServer(CDBFolderMysql* wrappedObj) { return wrappedObj->getServer();}
    const QString& getPort(CDBFolderMysql* wrappedObj) { return wrappedObj->getPort();}
    const QString& getUser(CDBFolderMysql* wrappedObj) { return wrappedObj->getUser();}
    const QString& getPasswd(CDBFolderMysql* wrappedObj) { return wrappedObj->getPasswd();}
    bool hasNoPasswd(CDBFolderMysql* wrappedObj) { return wrappedObj->hasNoPasswd();}
    QString getDBInfo(CDBFolderMysql* wrappedObj) { return wrappedObj->getDBInfo();}
    bool search(CDBFolderMysql* wrappedObj, const QString&  str, QSqlQuery&  query) { return wrappedObj->search(str, query);}
    void copyFolder(CDBFolderMysql* wrappedObj, quint64  child, quint64  parent) { return wrappedObj->copyFolder(child, parent);}
}; 

#endif