/**********************************************************************************************

This file was autogenerated by src/qmapshack/plugin/wrappers/createWrapper.py

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

**********************************************************************************************/

#ifndef CDBITEMWRAPPER_H
#define CDBITEMWRAPPER_H

#include <qobject.h>
#include "gis/db/CDBItem.h"



class CDBItemWrapper : public QObject
 {
    Q_OBJECT
public slots:
    quint64 getId(CDBItem* wrappedObj) { return wrappedObj->getId();}
    const QString& getKey(CDBItem* wrappedObj) { return wrappedObj->getKey();}
    QString getName(CDBItem* wrappedObj) { return wrappedObj->getName();}
    void toggle(CDBItem* wrappedObj) { return wrappedObj->toggle();}
    void remove(CDBItem* wrappedObj) { return wrappedObj->remove();}
    void updateAge(CDBItem* wrappedObj) { return wrappedObj->updateAge();}
}; 

#endif