/**********************************************************************************************

This file was autogenerated by src/qmapshack/plugin/wrappers/createWrapper.py

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

**********************************************************************************************/

#ifndef CDBPROJECTWRAPPER_H
#define CDBPROJECTWRAPPER_H

#include <qobject.h>
#include "gis/db/CDBProject.h"



class CDBProjectWrapper : public QObject
 {
    Q_OBJECT
public slots:
    void restoreDBLink(CDBProject* wrappedObj) { return wrappedObj->restoreDBLink();}
    bool canSave(CDBProject* wrappedObj) { return wrappedObj->canSave();}
    bool save(CDBProject* wrappedObj) { return wrappedObj->save();}
    quint64 getId(CDBProject* wrappedObj) { return wrappedObj->getId();}
    QString getDBName(CDBProject* wrappedObj) { return wrappedObj->getDBName();}
    QString getDBHost(CDBProject* wrappedObj) { return wrappedObj->getDBHost();}
    void postStatus(CDBProject* wrappedObj, bool  updateLostFound) { return wrappedObj->postStatus(updateLostFound);}
    void hideItems(CDBProject* wrappedObj, CEvtD2WHideItems *  evt) { return wrappedObj->hideItems(evt);}
    void update(CDBProject* wrappedObj) { return wrappedObj->update();}
}; 

#endif