/**********************************************************************************************

This file was autogenerated by src/qmapshack/plugin/wrappers/createWrapper.py

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

**********************************************************************************************/

#ifndef CGISLISTWKSWRAPPER_H
#define CGISLISTWKSWRAPPER_H

#include <qobject.h>
#include "gis/CGisListWks.h"

class IGisProject;
class CDBProject;


class CGisListWksWrapper : public QObject
 {
    Q_OBJECT
public slots:
    void setExternalMenu(CGisListWks* wrappedObj, QMenu *  project) { return wrappedObj->setExternalMenu(project);}
    bool hasProject(CGisListWks* wrappedObj, IGisProject * project) { return wrappedObj->hasProject(project);}
    IGisProject * getProjectByKey(CGisListWks* wrappedObj, const QString&  key) { return wrappedObj->getProjectByKey(key);}
    CDBProject * getProjectById(CGisListWks* wrappedObj, quint64  id, const QString&  db) { return wrappedObj->getProjectById(id, db);}
    bool event(CGisListWks* wrappedObj, QEvent *  e) { return wrappedObj->event(e);}
    void addProject(CGisListWks* wrappedObj, IGisProject * proj) { return wrappedObj->addProject(proj);}
    void removeDevice(CGisListWks* wrappedObj, const QString&  key) { return wrappedObj->removeDevice(key);}
    void slotLoadWorkspace(CGisListWks* wrappedObj) { return wrappedObj->slotLoadWorkspace();}
}; 

#endif