/**********************************************************************************************

This file was autogenerated by src/qmapshack/plugin/wrappers/createWrapper.py

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

**********************************************************************************************/

#ifndef CLOGPROJECTWRAPPER_H
#define CLOGPROJECTWRAPPER_H

#include <qobject.h>
#include "gis/suunto/CLogProject.h"



class CLogProjectWrapper : public QObject
 {
    Q_OBJECT
public slots:
    const QString getFileDialogFilter(CLogProject* wrappedObj) { return wrappedObj->getFileDialogFilter();}
    const QString getFileExtension(CLogProject* wrappedObj) { return wrappedObj->getFileExtension();}
    static void loadLog(CLogProject* wrappedObj, const QString & filename, ::CLogProject * project) { return wrappedObj->loadLog(filename, project);}
}; 

#endif