/**********************************************************************************************

This file was autogenerated by src/qmapshack/plugin/wrappers/createWrapper.py

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

**********************************************************************************************/

#ifndef CQMSPROJECTWRAPPER_H
#define CQMSPROJECTWRAPPER_H

#include <qobject.h>
#include "gis/qms/CQmsProject.h"



class CQmsProjectWrapper : public QObject
 {
    Q_OBJECT
public slots:
    const QString getFileDialogFilter(CQmsProject* wrappedObj) { return wrappedObj->getFileDialogFilter();}
    const QString getFileExtension(CQmsProject* wrappedObj) { return wrappedObj->getFileExtension();}
    bool canSave(CQmsProject* wrappedObj) { return wrappedObj->canSave();}
    static bool saveAs(CQmsProject* wrappedObj, const QString&  fn, IGisProject&  project) { return wrappedObj->saveAs(fn, project);}
}; 

#endif