/**********************************************************************************************

This file was autogenerated by src/qmapshack/plugin/wrappers/createWrapper.py

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

**********************************************************************************************/

#ifndef CSETUPDATABASEWRAPPER_H
#define CSETUPDATABASEWRAPPER_H

#include <qobject.h>
#include "gis/db/CSetupDatabase.h"



class CSetupDatabaseWrapper : public QObject
 {
    Q_OBJECT
public slots:
    bool isSqlite(CSetupDatabase* wrappedObj) { return wrappedObj->isSqlite();}
    bool isMysql(CSetupDatabase* wrappedObj) { return wrappedObj->isMysql();}
    bool noPasswd(CSetupDatabase* wrappedObj) { return wrappedObj->noPasswd();}
    QString getName(CSetupDatabase* wrappedObj) { return wrappedObj->getName();}
    QString getFilename(CSetupDatabase* wrappedObj) { return wrappedObj->getFilename();}
    QString getServer(CSetupDatabase* wrappedObj) { return wrappedObj->getServer();}
    QString getPort(CSetupDatabase* wrappedObj) { return wrappedObj->getPort();}
    QString getUser(CSetupDatabase* wrappedObj) { return wrappedObj->getUser();}
    QString getPasswd(CSetupDatabase* wrappedObj) { return wrappedObj->getPasswd();}
    void accept(CSetupDatabase* wrappedObj) { return wrappedObj->accept();}
}; 

#endif