/**********************************************************************************************

This file was autogenerated by src/qmapshack/plugin/wrappers/createWrapper.py

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

**********************************************************************************************/

#ifndef CSMLPROJECTWRAPPER_H
#define CSMLPROJECTWRAPPER_H

#include <qobject.h>
#include "gis/suunto/CSmlProject.h"



class CSmlProjectWrapper : public QObject
 {
    Q_OBJECT
public slots:
    const QString getFileDialogFilter(CSmlProject* wrappedObj) { return wrappedObj->getFileDialogFilter();}
    const QString getFileExtension(CSmlProject* wrappedObj) { return wrappedObj->getFileExtension();}
    static void loadSml(CSmlProject* wrappedObj, const QString & filename, ::CSmlProject * project) { return wrappedObj->loadSml(filename, project);}
}; 

#endif